name: Deploy Worker

on:
  push:
    branches: [main]
    paths:
      - "worker/**"
      - ".github/**"
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    defaults:
      run:
        working-directory: worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "worker/package-lock.json"
      - name: Install dependencies
        run: npm install
      - name: Publish
        run: npm run publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
